/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/10.1.52
 * Generated at: 2026-02-13 19:05:27 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import jakarta.servlet.*;
import jakarta.servlet.http.*;
import jakarta.servlet.jsp.*;
import java.net.http.*;
import java.net.URI;
import java.time.Duration;
import java.util.*;
import java.security.MessageDigest;
import java.nio.charset.StandardCharsets;
import java.net.URLEncoder;

public final class admin_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports,
                 org.apache.jasper.runtime.JspSourceDirectives {


    public String hashPassword(String input) {
        try {
            MessageDigest md = MessageDigest.getInstance("SHA-256");
            byte[] digest = md.digest(input.getBytes(StandardCharsets.UTF_8));
            StringBuilder sb = new StringBuilder();
            for (byte b : digest) {
                sb.append(String.format("%02x", b));
            }
            return sb.toString();
        } catch (Exception e) {
            return "";
        }
    }

    public String esc(String value) {
        if (value == null) {
            return "";
        }
        return value.replace("&", "&amp;")
                .replace("<", "&lt;")
                .replace(">", "&gt;")
                .replace("\"", "&quot;")
                .replace("'", "&#39;");
    }

    public boolean isLoggedIn(HttpSession session) {
        return session.getAttribute("authUser") != null;
    }

    public String currentUser(HttpSession session) {
        Object u = session.getAttribute("authUser");
        return u == null ? null : String.valueOf(u);
    }

    public boolean isAdmin(HttpSession session) {
        Object role = session.getAttribute("authRole");
        return role != null && "admin".equals(String.valueOf(role));
    }

    public Map<String, Object> q(String id, String text, String[] options, int answer) {
        Map<String, Object> question = new HashMap<String, Object>();
        question.put("id", id);
        question.put("text", text);
        question.put("options", options);
        question.put("answer", answer);
        return question;
    }

    public Map<String, Object> test(String id, String name, String tagline, int durationSec, double passPercent, List<Map<String, Object>> questions) {
        Map<String, Object> exam = new HashMap<String, Object>();
        exam.put("id", id);
        exam.put("name", name);
        exam.put("tagline", tagline);
        exam.put("durationSec", durationSec);
        exam.put("passPercent", passPercent);
        exam.put("questions", questions);
        return exam;
    }


    public String jsonEscape(String s) {
        if (s == null) return "";
        return s.replace("\\", "\\\\").replace("\"", "\\\"").replace("\n", "\\n").replace("\r", "\\r");
    }

    public String jsonUnescape(String s) {
        if (s == null) return "";
        StringBuilder out = new StringBuilder();
        for (int i = 0; i < s.length(); i++) {
            char c = s.charAt(i);
            if (c == '\\' && i + 1 < s.length()) {
                char n = s.charAt(++i);
                if (n == 'n') out.append('\n');
                else if (n == 'r') out.append('\r');
                else if (n == 't') out.append('\t');
                else if (n == '"') out.append('"');
                else if (n == '\\') out.append('\\');
                else if (n == 'u' && i + 4 < s.length()) {
                    String hex = s.substring(i + 1, i + 5);
                    try {
                        out.append((char) Integer.parseInt(hex, 16));
                        i += 4;
                    } catch (Exception ignore) {
                        out.append("\\u").append(hex);
                        i += 4;
                    }
                } else {
                    out.append(n);
                }
            } else {
                out.append(c);
            }
        }
        return out.toString();
    }

    public String extractJsonStringField(String json, String key) {
        if (json == null || key == null || key.isEmpty()) return null;
        String needle = "\"" + key + "\"";
        int keyPos = json.indexOf(needle);
        while (keyPos >= 0) {
            int colon = json.indexOf(':', keyPos + needle.length());
            if (colon < 0) return null;
            int i = colon + 1;
            while (i < json.length() && Character.isWhitespace(json.charAt(i))) {
                i++;
            }
            if (i < json.length() && json.charAt(i) == '"') {
                i++;
                StringBuilder sb = new StringBuilder();
                boolean escaped = false;
                while (i < json.length()) {
                    char c = json.charAt(i++);
                    if (escaped) {
                        sb.append('\\').append(c);
                        escaped = false;
                    } else if (c == '\\') {
                        escaped = true;
                    } else if (c == '"') {
                        return jsonUnescape(sb.toString());
                    } else {
                        sb.append(c);
                    }
                }
                return null;
            }
            keyPos = json.indexOf(needle, keyPos + needle.length());
        }
        return null;
    }

    public String extractFirstContent(String json) {
        return extractJsonStringField(json, "content");
    }

    public String extractFirstGeminiText(String json) {
        return extractJsonStringField(json, "text");
    }

  private static final jakarta.servlet.jsp.JspFactory _jspxFactory =
          jakarta.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(1);
    _jspx_dependants.put("/exam-common.jspf", Long.valueOf(1771007077865L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.LinkedHashSet<>(7);
    _jspx_imports_packages.add("java.util");
    _jspx_imports_packages.add("jakarta.servlet");
    _jspx_imports_packages.add("jakarta.servlet.http");
    _jspx_imports_packages.add("jakarta.servlet.jsp");
    _jspx_imports_packages.add("java.net.http");
    _jspx_imports_classes = new java.util.LinkedHashSet<>(7);
    _jspx_imports_classes.add("java.net.URLEncoder");
    _jspx_imports_classes.add("java.security.MessageDigest");
    _jspx_imports_classes.add("java.time.Duration");
    _jspx_imports_classes.add("java.net.URI");
    _jspx_imports_classes.add("java.nio.charset.StandardCharsets");
  }

  private volatile jakarta.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public boolean getErrorOnELNotFound() {
    return false;
  }

  public jakarta.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final jakarta.servlet.http.HttpServletRequest request, final jakarta.servlet.http.HttpServletResponse response)
      throws java.io.IOException, jakarta.servlet.ServletException {

    if (!jakarta.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final jakarta.servlet.jsp.PageContext pageContext;
    jakarta.servlet.http.HttpSession session = null;
    final jakarta.servlet.ServletContext application;
    final jakarta.servlet.ServletConfig config;
    jakarta.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    jakarta.servlet.jsp.JspWriter _jspx_out = null;
    jakarta.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write('\n');
      out.write('\n');
      out.write('\n');
      out.write('\n');

    request.setCharacterEncoding("UTF-8");

    synchronized (application) {
        if (application.getAttribute("users") == null) {
            application.setAttribute("users", new HashMap<String, Map<String, String>>());
        }
        if (application.getAttribute("attempts") == null) {
            application.setAttribute("attempts", new ArrayList<Map<String, Object>>());
        }
        if (application.getAttribute("testCatalog") == null) {
            List<Map<String, Object>> catalog = new ArrayList<Map<String, Object>>();

            List<Map<String, Object>> t1 = new ArrayList<Map<String, Object>>();
            t1.add(q("F1", "Which protocol encrypts website traffic by default?", new String[]{"HTTP", "FTP", "HTTPS", "IMAP"}, 2));
            t1.add(q("F2", "Which data structure follows Last-In-First-Out order?", new String[]{"Queue", "Stack", "Tree", "Graph"}, 1));
            t1.add(q("F3", "What does SQL stand for?", new String[]{"Structured Query Language", "Simple Query Logic", "Secure Queue Layer", "System Query Link"}, 0));
            t1.add(q("F4", "Which Java keyword creates a subclass from a parent class?", new String[]{"extends", "implements", "inherits", "super"}, 0));
            t1.add(q("F5", "Big-O for binary search on sorted data is", new String[]{"O(n)", "O(log n)", "O(n log n)", "O(1)"}, 1));
            t1.add(q("F6", "Which HTML tag is used for the largest heading?", new String[]{"<head>", "<h6>", "<h1>", "<header>"}, 2));
            t1.add(q("F7", "Which SQL clause filters rows before grouping?", new String[]{"HAVING", "ORDER BY", "GROUP BY", "WHERE"}, 3));
            t1.add(q("F8", "Which of these is a NoSQL database?", new String[]{"MySQL", "PostgreSQL", "MongoDB", "Oracle"}, 2));
            t1.add(q("F9", "In CSS, which property controls text color?", new String[]{"font-color", "text-color", "color", "foreground"}, 2));
            t1.add(q("F10", "Which HTTP status means Not Found?", new String[]{"200", "302", "401", "404"}, 3));
            t1.add(q("F11", "Which command in Git uploads local commits to remote?", new String[]{"git clone", "git pull", "git push", "git merge"}, 2));
            t1.add(q("F12", "Which one is a strongly typed language?", new String[]{"Java", "HTML", "CSS", "SQL"}, 0));
            catalog.add(test("FOUND", "Foundations Assessment", "Core software and web fundamentals", 12 * 60, 55.0, t1));

            List<Map<String, Object>> t2 = new ArrayList<Map<String, Object>>();
            t2.add(q("A1", "Which model architecture powers most modern LLM chat systems?", new String[]{"CNN", "Transformer", "RNN", "SVM"}, 1));
            t2.add(q("A2", "Precision measures", new String[]{"Correct positives among predicted positives", "Correct positives among all actual positives", "Overall correctness", "Training speed"}, 0));
            t2.add(q("A3", "Overfitting means", new String[]{"Model performs well on unseen data", "Model memorizes training data and generalizes poorly", "Model uses too little data", "Model has low variance"}, 1));
            t2.add(q("A4", "Which task is supervised learning?", new String[]{"Clustering customers", "Dimensionality reduction", "Spam classification", "Topic modeling"}, 2));
            t2.add(q("A5", "Gradient descent updates parameters using", new String[]{"Random guessing", "Loss gradients", "Manual tuning", "Hash maps"}, 1));
            t2.add(q("A6", "A confusion matrix is used for", new String[]{"Database joins", "Classification evaluation", "Network routing", "Code linting"}, 1));
            t2.add(q("A7", "Which metric is better for imbalanced binary classes?", new String[]{"Accuracy only", "F1 score", "Epoch count", "Latency"}, 1));
            t2.add(q("A8", "Tokenization in NLP is", new String[]{"Encrypting text", "Breaking text into units", "Compressing images", "Balancing labels"}, 1));
            t2.add(q("A9", "ReLU is", new String[]{"A loss function", "An optimizer", "An activation function", "A tokenizer"}, 2));
            t2.add(q("A10", "Train/validation split helps", new String[]{"Detect generalization", "Speed up hardware", "Avoid using labels", "Remove features"}, 0));
            catalog.add(test("AI", "AI Systems Readiness", "Applied ML, evaluation and deployment concepts", 10 * 60, 60.0, t2));

            List<Map<String, Object>> t3 = new ArrayList<Map<String, Object>>();
            t3.add(q("C1", "Which attack injects malicious SQL statements?", new String[]{"DDoS", "XSS", "SQL Injection", "CSRF"}, 2));
            t3.add(q("C2", "MFA stands for", new String[]{"Managed Firewall Access", "Multi-Factor Authentication", "Master File Allocation", "Main Function API"}, 1));
            t3.add(q("C3", "Principle of least privilege means", new String[]{"Give all users admin", "Grant minimum required access", "Share credentials", "Disable logging"}, 1));
            t3.add(q("C4", "Which header reduces XSS risk in browsers?", new String[]{"Content-Security-Policy", "Cache-Control", "ETag", "Accept-Language"}, 0));
            t3.add(q("C5", "Brute force protection usually includes", new String[]{"Unlimited retries", "Rate limiting and lockout", "Plain text passwords", "Open ports"}, 1));
            t3.add(q("C6", "Which one is symmetric encryption?", new String[]{"RSA", "ECC", "AES", "DSA"}, 2));
            t3.add(q("C7", "Phishing primarily targets", new String[]{"Hardware heat", "Human trust", "Compiler speed", "DNS TTL"}, 1));
            t3.add(q("C8", "Which log is key for incident response?", new String[]{"Authentication logs", "Font logs", "Theme logs", "Cache logos"}, 0));
            t3.add(q("C9", "HTTPS certificate validation helps prevent", new String[]{"MITM attacks", "Memory leaks", "Race conditions", "Deadlocks"}, 0));
            t3.add(q("C10", "A secure password should be", new String[]{"Short and reused", "Long and unique", "Only numeric", "Stored in plain text"}, 1));
            catalog.add(test("CYBER", "Cyber Operations Drill", "Security, authentication and secure web operations", 9 * 60, 65.0, t3));

            application.setAttribute("testCatalog", catalog);
            application.setAttribute("questionBank", t1);
        }
    }

    Map<String, Map<String, String>> users = (Map<String, Map<String, String>>) application.getAttribute("users");
    List<Map<String, Object>> attempts = (List<Map<String, Object>>) application.getAttribute("attempts");
    List<Map<String, Object>> testCatalog = (List<Map<String, Object>>) application.getAttribute("testCatalog");

    synchronized (application) {
        if (!users.containsKey("admin")) {
            Map<String, String> admin = new HashMap<String, String>();
            admin.put("fullName", "System Admin");
            admin.put("username", "admin");
            admin.put("passwordHash", hashPassword("admin123"));
            admin.put("createdAt", new Date().toString());
            admin.put("role", "admin");
            users.put("admin", admin);
        }
    }

    Map<String, Map<String, Object>> testIndex = new HashMap<String, Map<String, Object>>();
    int totalQuestionsAcrossTests = 0;
    for (Map<String, Object> t : testCatalog) {
        String testId = String.valueOf(t.get("id"));
        testIndex.put(testId, t);
        List<Map<String, Object>> qs = (List<Map<String, Object>>) t.get("questions");
        totalQuestionsAcrossTests += qs.size();
    }

      out.write('\r');
      out.write('\n');
      out.write('\n');
      out.write('\n');

    if (!isLoggedIn(session)) {
        response.sendRedirect("login.jsp");
        return;
    }
    if (!isAdmin(session)) {
        response.sendRedirect("dashboard.jsp");
        return;
    }

    String msg = "";
    String err = "";

    if ("POST".equalsIgnoreCase(request.getMethod())) {
        String action = request.getParameter("action");

        synchronized (application) {
            if ("createTest".equals(action)) {
                String id = request.getParameter("testId");
                String name = request.getParameter("testName");
                String tagline = request.getParameter("tagline");
                String durationMin = request.getParameter("durationMin");
                String passPercent = request.getParameter("passPercent");

                id = id == null ? "" : id.trim().toUpperCase();
                name = name == null ? "" : name.trim();
                tagline = tagline == null ? "" : tagline.trim();

                int durationSec = 0;
                double pass = 0;

                try {
                    durationSec = Integer.parseInt(durationMin) * 60;
                    pass = Double.parseDouble(passPercent);
                } catch (Exception ex) {
                    durationSec = 0;
                }

                if (id.isEmpty() || name.isEmpty() || durationSec <= 0 || pass <= 0 || pass > 100) {
                    err = "Invalid test details.";
                } else if (testIndex.containsKey(id)) {
                    err = "Test ID already exists.";
                } else {
                    List<Map<String, Object>> qs = new ArrayList<Map<String, Object>>();
                    testCatalog.add(test(id, name, tagline, durationSec, pass, qs));
                    msg = "Test created: " + id;
                }
            }

            if ("deleteTest".equals(action)) {
                String id = request.getParameter("testId");
                id = id == null ? "" : id.trim().toUpperCase();
                boolean removed = false;
                for (Iterator<Map<String, Object>> it = testCatalog.iterator(); it.hasNext();) {
                    Map<String, Object> t = it.next();
                    if (id.equals(String.valueOf(t.get("id")))) {
                        it.remove();
                        removed = true;
                        break;
                    }
                }
                if (removed) {
                    msg = "Test removed: " + id;
                } else {
                    err = "Test not found.";
                }
            }

            if ("addQuestion".equals(action)) {
                String id = request.getParameter("testId");
                String qid = request.getParameter("qid");
                String qtext = request.getParameter("qtext");
                String o1 = request.getParameter("o1");
                String o2 = request.getParameter("o2");
                String o3 = request.getParameter("o3");
                String o4 = request.getParameter("o4");
                String answer = request.getParameter("answer");

                id = id == null ? "" : id.trim().toUpperCase();
                qid = qid == null ? "" : qid.trim().toUpperCase();
                qtext = qtext == null ? "" : qtext.trim();
                o1 = o1 == null ? "" : o1.trim();
                o2 = o2 == null ? "" : o2.trim();
                o3 = o3 == null ? "" : o3.trim();
                o4 = o4 == null ? "" : o4.trim();

                Map<String, Object> t = testIndex.get(id);
                int ans = -1;
                try {
                    ans = Integer.parseInt(answer);
                } catch (Exception ignore) {
                    ans = -1;
                }

                if (t == null) {
                    err = "Target test not found.";
                } else if (qid.isEmpty() || qtext.isEmpty() || o1.isEmpty() || o2.isEmpty() || o3.isEmpty() || o4.isEmpty() || ans < 0 || ans > 3) {
                    err = "Invalid question payload.";
                } else {
                    List<Map<String, Object>> qs = (List<Map<String, Object>>) t.get("questions");
                    boolean exists = false;
                    for (Map<String, Object> q : qs) {
                        if (qid.equals(String.valueOf(q.get("id")))) {
                            exists = true;
                            break;
                        }
                    }
                    if (exists) {
                        err = "Question ID already exists in this test.";
                    } else {
                        qs.add(q(qid, qtext, new String[]{o1, o2, o3, o4}, ans));
                        msg = "Question added to " + id;
                    }
                }
            }

            if ("deleteQuestion".equals(action)) {
                String id = request.getParameter("testId");
                String qid = request.getParameter("qid");
                id = id == null ? "" : id.trim().toUpperCase();
                qid = qid == null ? "" : qid.trim().toUpperCase();

                Map<String, Object> t = testIndex.get(id);
                if (t == null) {
                    err = "Target test not found.";
                } else {
                    List<Map<String, Object>> qs = (List<Map<String, Object>>) t.get("questions");
                    boolean removed = false;
                    for (Iterator<Map<String, Object>> it = qs.iterator(); it.hasNext();) {
                        Map<String, Object> q = it.next();
                        if (qid.equals(String.valueOf(q.get("id")))) {
                            it.remove();
                            removed = true;
                            break;
                        }
                    }
                    if (removed) {
                        msg = "Question removed: " + qid;
                    } else {
                        err = "Question ID not found in test.";
                    }
                }
            }

            if ("importAI".equals(action) || "generateAI".equals(action)) {
                String payload = request.getParameter("aiPayload");
                boolean replaceExisting = "on".equals(request.getParameter("replaceExisting"));
                if ("generateAI".equals(action)) {
                    String apiKey = request.getParameter("geminiApiKey");
                    if (apiKey == null || apiKey.trim().isEmpty()) {
                        apiKey = request.getParameter("openaiApiKey");
                    }
                    String topic = request.getParameter("genTopic");
                    String level = request.getParameter("genLevel");
                    String countStr = request.getParameter("genCount");
                    String genTestId = request.getParameter("genTestId");
                    String genTestName = request.getParameter("genTestName");
                    String genTagline = request.getParameter("genTagline");
                    String genDuration = request.getParameter("genDurationMin");
                    String genPass = request.getParameter("genPassPercent");

                    apiKey = apiKey == null ? "" : apiKey.trim();
                    topic = topic == null ? "" : topic.trim();
                    level = level == null ? "" : level.trim();
                    countStr = countStr == null ? "10" : countStr.trim();
                    genTestId = genTestId == null ? "" : genTestId.trim().toUpperCase();
                    genTestName = genTestName == null ? "" : genTestName.trim();
                    genTagline = genTagline == null ? "" : genTagline.trim();
                    genDuration = genDuration == null ? "20" : genDuration.trim();
                    genPass = genPass == null ? "60" : genPass.trim();

                    if (apiKey.isEmpty()) {
                        err = "Gemini API key is required for direct generation.";
                    } else if (apiKey.contains("HTTP Status") || apiKey.contains("Internal Server Error")) {
                        err = "Invalid Gemini API key value pasted. Please paste only the API key.";
                    } else if (apiKey.matches(".*\\s+.*")) {
                        err = "Invalid Gemini API key format (contains whitespace/newline).";
                    } else {
                        int qCount = 10;
                        try {
                            qCount = Integer.parseInt(countStr);
                        } catch (Exception ignore) {
                            qCount = 10;
                        }
                        if (qCount < 3) qCount = 3;
                        if (qCount > 50) qCount = 50;

                        String prompt = ""
                                + "Create a multiple-choice exam strictly in the format below.\n"
                                + "No markdown, no explanation, no extra text.\n"
                                + "Topic: " + topic + "\n"
                                + "Level: " + level + "\n"
                                + "Question count: " + qCount + "\n\n"
                                + "FORMAT:\n"
                                + "TEST_ID: " + genTestId + "\n"
                                + "TEST_NAME: " + genTestName + "\n"
                                + "TAGLINE: " + genTagline + "\n"
                                + "DURATION_MIN: " + genDuration + "\n"
                                + "PASS_PERCENT: " + genPass + "\n"
                                + "Q\\t<QUESTION_ID>\\t<QUESTION_TEXT>\\t<OPTION1>\\t<OPTION2>\\t<OPTION3>\\t<OPTION4>\\t<CORRECT_OPTION_INDEX_0_TO_3>\n\n"
                                + "Rules:\n"
                                + "- Provide exactly " + qCount + " Q lines\n"
                                + "- Use unique QUESTION_ID values\n"
                                + "- Correct index must be 0,1,2 or 3\n"
                                + "- Keep options concise and valid.";

                        String reqJson = "{"
                                + "\"contents\":[{"
                                + "\"role\":\"user\","
                                + "\"parts\":[{\"text\":\"" + jsonEscape(prompt) + "\"}]"
                                + "}],"
                                + "\"generationConfig\":{"
                                + "\"temperature\":0.4"
                                + "}"
                                + "}";

                        try {
                            HttpClient client = HttpClient.newBuilder()
                                    .connectTimeout(Duration.ofSeconds(20))
                                    .build();
                            String geminiUrl = "https://generativelanguage.googleapis.com/v1beta/models/gemini-2.5-flash:generateContent?key=" + URLEncoder.encode(apiKey, "UTF-8");
                            HttpRequest httpReq = HttpRequest.newBuilder()
                                    .uri(URI.create(geminiUrl))
                                    .header("Content-Type", "application/json")
                                    .timeout(Duration.ofSeconds(60))
                                    .POST(HttpRequest.BodyPublishers.ofString(reqJson))
                                    .build();

                            HttpResponse<String> aiResp = null;
                            for (int attempt = 0; attempt < 2; attempt++) {
                                aiResp = client.send(httpReq, HttpResponse.BodyHandlers.ofString());
                                if (aiResp.statusCode() != 429 || attempt == 1) {
                                    break;
                                }
                                try {
                                    Thread.sleep(1500);
                                } catch (InterruptedException ie) {
                                    Thread.currentThread().interrupt();
                                }
                            }

                            if (aiResp != null && aiResp.statusCode() >= 200 && aiResp.statusCode() < 300) {
                                payload = extractFirstGeminiText(aiResp.body());
                                if (payload == null || payload.trim().isEmpty()) {
                                    err = "Could not parse AI response content.";
                                } else {
                                    payload = payload.trim();
                                }
                            } else if (aiResp != null) {
                                String apiMsg = extractJsonStringField(aiResp.body(), "message");
                                if (apiMsg == null || apiMsg.trim().isEmpty()) {
                                    err = "Gemini API error: HTTP " + aiResp.statusCode();
                                } else {
                                    err = "Gemini API error: HTTP " + aiResp.statusCode() + " - " + apiMsg;
                                }
                            } else {
                                err = "Gemini API call failed: empty response.";
                            }
                        } catch (Exception ex) {
                            err = "Gemini API call failed: " + ex.getMessage();
                        }
                    }
                }

                payload = payload == null ? "" : payload.trim();
                if (err.isEmpty() && payload.isEmpty()) {
                    err = "AI payload is empty.";
                } else if (err.isEmpty()) {
                    String testId = "";
                    String testName = "";
                    String tagline = "";
                    int durationMin = 0;
                    double passPercent = 0.0;
                    List<Map<String, Object>> importedQuestions = new ArrayList<Map<String, Object>>();
                    Set<String> seenIds = new HashSet<String>();

                    String[] lines = payload.split("\\r?\\n");
                    for (int i = 0; i < lines.length; i++) {
                        String raw = lines[i];
                        String line = raw == null ? "" : raw.trim();
                        if (line.isEmpty() || line.startsWith("#")) {
                            continue;
                        }

                        if (line.startsWith("TEST_ID:")) {
                            testId = line.substring("TEST_ID:".length()).trim().toUpperCase();
                            continue;
                        }
                        if (line.startsWith("TEST_NAME:")) {
                            testName = line.substring("TEST_NAME:".length()).trim();
                            continue;
                        }
                        if (line.startsWith("TAGLINE:")) {
                            tagline = line.substring("TAGLINE:".length()).trim();
                            continue;
                        }
                        if (line.startsWith("DURATION_MIN:")) {
                            try {
                                durationMin = Integer.parseInt(line.substring("DURATION_MIN:".length()).trim());
                            } catch (Exception ex) {
                                err = "Invalid DURATION_MIN value.";
                            }
                            continue;
                        }
                        if (line.startsWith("PASS_PERCENT:")) {
                            try {
                                passPercent = Double.parseDouble(line.substring("PASS_PERCENT:".length()).trim());
                            } catch (Exception ex) {
                                err = "Invalid PASS_PERCENT value.";
                            }
                            continue;
                        }

                        if (line.startsWith("Q\t")) {
                            String[] parts = line.split("\\t", -1);
                            if (parts.length < 8) {
                                err = "Invalid question row format. Expected 8 tab-separated columns.";
                                break;
                            }
                            String qid = parts[1].trim().toUpperCase();
                            String qtext = parts[2].trim();
                            String o1 = parts[3].trim();
                            String o2 = parts[4].trim();
                            String o3 = parts[5].trim();
                            String o4 = parts[6].trim();
                            int ans = -1;
                            try {
                                ans = Integer.parseInt(parts[7].trim());
                            } catch (Exception ignore) {
                                ans = -1;
                            }

                            if (qid.isEmpty() || qtext.isEmpty() || o1.isEmpty() || o2.isEmpty() || o3.isEmpty() || o4.isEmpty() || ans < 0 || ans > 3) {
                                err = "Invalid question values found in payload.";
                                break;
                            }
                            if (seenIds.contains(qid)) {
                                err = "Duplicate question ID in payload: " + qid;
                                break;
                            }
                            seenIds.add(qid);
                            importedQuestions.add(q(qid, qtext, new String[]{o1, o2, o3, o4}, ans));
                        }
                    }

                    if (err.isEmpty()) {
                        if (testId.isEmpty() || testName.isEmpty() || durationMin <= 0 || passPercent <= 0 || passPercent > 100 || importedQuestions.isEmpty()) {
                            err = "Payload missing required fields or questions.";
                        } else {
                            Map<String, Object> existing = testIndex.get(testId);
                            if (existing != null && !replaceExisting) {
                                err = "Test ID already exists. Enable replace to overwrite.";
                            } else {
                                if (existing != null) {
                                    for (Iterator<Map<String, Object>> it = testCatalog.iterator(); it.hasNext();) {
                                        Map<String, Object> t = it.next();
                                        if (testId.equals(String.valueOf(t.get("id")))) {
                                            it.remove();
                                            break;
                                        }
                                    }
                                }
                                testCatalog.add(test(testId, testName, tagline, durationMin * 60, passPercent, importedQuestions));
                                msg = "AI test imported: " + testId + " (" + importedQuestions.size() + " questions)";
                            }
                        }
                    }
                }
            }
        }

        response.sendRedirect("admin.jsp?msg=" + URLEncoder.encode(msg, "UTF-8") + "&err=" + URLEncoder.encode(err, "UTF-8"));
        return;
    }

    String msgQ = request.getParameter("msg");
    String errQ = request.getParameter("err");

      out.write("\n");
      out.write("<!DOCTYPE html>\n");
      out.write("<html>\n");
      out.write("<head>\n");
      out.write("    <meta charset=\"UTF-8\">\n");
      out.write("    <meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">\n");
      out.write("    <title>Admin Control | Exam Grid 2050</title>\n");
      out.write("    <script src=\"https://cdn.tailwindcss.com\"></script>\n");
      out.write("    <script>\n");
      out.write("        tailwind.config = {\n");
      out.write("            theme: {\n");
      out.write("                extend: {\n");
      out.write("                    fontFamily: {\n");
      out.write("                        display: ['Orbitron', 'sans-serif'],\n");
      out.write("                        body: ['Space Grotesk', 'sans-serif']\n");
      out.write("                    }\n");
      out.write("                }\n");
      out.write("            }\n");
      out.write("        }\n");
      out.write("    </script>\n");
      out.write("    <style>\n");
      out.write("        @import url('https://fonts.googleapis.com/css2?family=Orbitron:wght@500;700;800&family=Space+Grotesk:wght@400;500;600;700&display=swap');\n");
      out.write("    </style>\n");
      out.write("</head>\n");
      out.write("<body class=\"min-h-screen font-body text-slate-100 bg-slate-950\">\n");
      out.write("<div class=\"fixed inset-0 -z-10 bg-[radial-gradient(circle_at_15%_10%,rgba(34,211,238,0.2),transparent_30%),radial-gradient(circle_at_80%_5%,rgba(16,185,129,0.25),transparent_34%),linear-gradient(145deg,#020617,#0b1123,#111827)]\"></div>\n");
      out.write("<div class=\"max-w-7xl mx-auto px-4 py-8\">\n");
      out.write("    <div class=\"flex items-center justify-between\">\n");
      out.write("        <div>\n");
      out.write("            <p class=\"text-xs uppercase tracking-[0.25em] text-emerald-300\">Administrator</p>\n");
      out.write("            <h1 class=\"font-display text-3xl md:text-4xl\">Test Control Panel</h1>\n");
      out.write("        </div>\n");
      out.write("        <a href=\"dashboard.jsp\" class=\"px-4 py-2 rounded-xl border border-white/20 hover:bg-white/10\">Dashboard</a>\n");
      out.write("    </div>\n");
      out.write("\n");
      out.write("    ");
 if (msgQ != null && !msgQ.trim().isEmpty()) { 
      out.write("\n");
      out.write("    <div class=\"mt-4 rounded-lg border border-emerald-400/40 bg-emerald-500/15 px-4 py-3 text-emerald-200\">");
      out.print( esc(msgQ) );
      out.write("</div>\n");
      out.write("    ");
 } 
      out.write("\n");
      out.write("    ");
 if (errQ != null && !errQ.trim().isEmpty()) { 
      out.write("\n");
      out.write("    <div class=\"mt-4 rounded-lg border border-red-400/40 bg-red-500/15 px-4 py-3 text-red-200\">");
      out.print( esc(errQ) );
      out.write("</div>\n");
      out.write("    ");
 } 
      out.write("\n");
      out.write("\n");
      out.write("    <section class=\"rounded-2xl border border-cyan-300/25 bg-cyan-500/10 p-5 mt-6\">\n");
      out.write("        <h2 class=\"font-display text-2xl\">AI Test Generator (ChatGPT)</h2>\n");
      out.write("        <p class=\"text-sm text-slate-300 mt-1\">You can generate directly with Gemini API, or use prompt + paste mode.</p>\n");
      out.write("\n");
      out.write("        <form method=\"post\" class=\"grid gap-3 mt-4 rounded-xl border border-emerald-300/25 bg-emerald-500/10 p-4\">\n");
      out.write("            <input type=\"hidden\" name=\"action\" value=\"generateAI\">\n");
      out.write("            <h3 class=\"font-display text-lg text-emerald-200\">Direct Generate and Import</h3>\n");
      out.write("            <input type=\"password\" name=\"geminiApiKey\" placeholder=\"Gemini API key\" class=\"rounded-lg bg-slate-900/70 border border-white/20 px-3 py-2\" required>\n");
      out.write("            <div class=\"grid md:grid-cols-3 gap-3\">\n");
      out.write("                <input name=\"genTopic\" placeholder=\"Topic (e.g. Internet of Things)\" class=\"rounded-lg bg-slate-900/70 border border-white/20 px-3 py-2\" required>\n");
      out.write("                <input name=\"genLevel\" placeholder=\"Level (Beginner/Intermediate/Advanced)\" class=\"rounded-lg bg-slate-900/70 border border-white/20 px-3 py-2\" required>\n");
      out.write("                <input type=\"number\" name=\"genCount\" min=\"3\" max=\"50\" value=\"10\" placeholder=\"Question count\" class=\"rounded-lg bg-slate-900/70 border border-white/20 px-3 py-2\" required>\n");
      out.write("            </div>\n");
      out.write("            <div class=\"grid md:grid-cols-3 gap-3\">\n");
      out.write("                <input name=\"genTestId\" placeholder=\"Test ID (e.g. IOTINT)\" class=\"rounded-lg bg-slate-900/70 border border-white/20 px-3 py-2\" required>\n");
      out.write("                <input name=\"genTestName\" placeholder=\"Test Name\" class=\"rounded-lg bg-slate-900/70 border border-white/20 px-3 py-2\" required>\n");
      out.write("                <input name=\"genTagline\" placeholder=\"Tagline\" class=\"rounded-lg bg-slate-900/70 border border-white/20 px-3 py-2\">\n");
      out.write("            </div>\n");
      out.write("            <div class=\"grid md:grid-cols-3 gap-3\">\n");
      out.write("                <input type=\"number\" name=\"genDurationMin\" min=\"1\" value=\"20\" placeholder=\"Duration (min)\" class=\"rounded-lg bg-slate-900/70 border border-white/20 px-3 py-2\" required>\n");
      out.write("                <input type=\"number\" step=\"0.1\" name=\"genPassPercent\" min=\"1\" max=\"100\" value=\"60\" placeholder=\"Pass %\" class=\"rounded-lg bg-slate-900/70 border border-white/20 px-3 py-2\" required>\n");
      out.write("                <label class=\"inline-flex items-center gap-2 text-sm text-slate-200 rounded-lg border border-white/20 px-3 py-2\">\n");
      out.write("                    <input type=\"checkbox\" name=\"replaceExisting\" class=\"accent-cyan-400\">\n");
      out.write("                    Replace if ID exists\n");
      out.write("                </label>\n");
      out.write("            </div>\n");
      out.write("            <button class=\"rounded-xl py-2 bg-gradient-to-r from-emerald-400 to-cyan-400 text-slate-900 font-semibold\">Generate with API and Import</button>\n");
      out.write("            <p class=\"text-xs text-slate-300\">Security: key is used only for this request and not stored in tests/users.</p>\n");
      out.write("        </form>\n");
      out.write("\n");
      out.write("        <div class=\"grid md:grid-cols-4 gap-3 mt-4\">\n");
      out.write("            <input id=\"aiTopic\" placeholder=\"Topic (e.g. Data Structures)\" class=\"rounded-lg bg-slate-900/70 border border-white/20 px-3 py-2\">\n");
      out.write("            <input id=\"aiLevel\" placeholder=\"Level (e.g. Intermediate)\" class=\"rounded-lg bg-slate-900/70 border border-white/20 px-3 py-2\">\n");
      out.write("            <input id=\"aiCount\" type=\"number\" min=\"3\" value=\"10\" placeholder=\"Question count\" class=\"rounded-lg bg-slate-900/70 border border-white/20 px-3 py-2\">\n");
      out.write("            <button type=\"button\" onclick=\"buildAIPrompt()\" class=\"rounded-xl py-2 bg-gradient-to-r from-cyan-400 to-emerald-400 text-slate-900 font-semibold\">Generate ChatGPT Prompt</button>\n");
      out.write("        </div>\n");
      out.write("\n");
      out.write("        <textarea id=\"aiPromptBox\" class=\"mt-3 w-full min-h-40 rounded-lg bg-slate-900/70 border border-white/20 px-3 py-2 text-sm\" placeholder=\"Prompt for ChatGPT will appear here...\"></textarea>\n");
      out.write("        <div class=\"flex gap-3 mt-2\">\n");
      out.write("            <button type=\"button\" onclick=\"copyAIPrompt()\" class=\"rounded-lg px-3 py-2 border border-cyan-300/40 text-cyan-200 hover:bg-cyan-500/20\">Copy Prompt</button>\n");
      out.write("            <a href=\"https://chatgpt.com/\" target=\"_blank\" class=\"rounded-lg px-3 py-2 border border-emerald-300/40 text-emerald-200 hover:bg-emerald-500/20\">Open ChatGPT</a>\n");
      out.write("        </div>\n");
      out.write("\n");
      out.write("        <form method=\"post\" class=\"mt-5 grid gap-3\">\n");
      out.write("            <input type=\"hidden\" name=\"action\" value=\"importAI\">\n");
      out.write("            <label class=\"text-sm text-slate-300\">Paste ChatGPT output in required format:</label>\n");
      out.write("            <textarea name=\"aiPayload\" class=\"w-full min-h-64 rounded-lg bg-slate-900/70 border border-white/20 px-3 py-2 font-mono text-xs\" placeholder=\"TEST_ID: DS01\n");
      out.write("TEST_NAME: Data Structures Core\n");
      out.write("TAGLINE: Arrays, stacks, queues and trees\n");
      out.write("DURATION_MIN: 20\n");
      out.write("PASS_PERCENT: 60\n");
      out.write("Q	DSQ1	What is the amortized complexity of dynamic array append?	O(n)	O(1) average	O(log n)	O(n log n)	1\"></textarea>\n");
      out.write("            <label class=\"inline-flex items-center gap-2 text-sm text-slate-300\">\n");
      out.write("                <input type=\"checkbox\" name=\"replaceExisting\" class=\"accent-cyan-400\">\n");
      out.write("                Replace existing test if TEST_ID already exists\n");
      out.write("            </label>\n");
      out.write("            <button class=\"rounded-xl py-2 bg-gradient-to-r from-emerald-400 to-cyan-400 text-slate-900 font-semibold\">Import AI Test</button>\n");
      out.write("        </form>\n");
      out.write("    </section>\n");
      out.write("\n");
      out.write("    <div class=\"grid lg:grid-cols-2 gap-4 mt-6\">\n");
      out.write("        <section class=\"rounded-2xl border border-white/15 bg-white/10 p-5\">\n");
      out.write("            <h2 class=\"font-display text-xl\">Create Test</h2>\n");
      out.write("            <form method=\"post\" class=\"grid gap-3 mt-3\">\n");
      out.write("                <input type=\"hidden\" name=\"action\" value=\"createTest\">\n");
      out.write("                <input name=\"testId\" placeholder=\"Test ID (e.g. DSA)\" class=\"rounded-lg bg-slate-900/70 border border-white/20 px-3 py-2\" required>\n");
      out.write("                <input name=\"testName\" placeholder=\"Test Name\" class=\"rounded-lg bg-slate-900/70 border border-white/20 px-3 py-2\" required>\n");
      out.write("                <input name=\"tagline\" placeholder=\"Tagline\" class=\"rounded-lg bg-slate-900/70 border border-white/20 px-3 py-2\">\n");
      out.write("                <div class=\"grid grid-cols-2 gap-3\">\n");
      out.write("                    <input type=\"number\" name=\"durationMin\" min=\"1\" placeholder=\"Duration (min)\" class=\"rounded-lg bg-slate-900/70 border border-white/20 px-3 py-2\" required>\n");
      out.write("                    <input type=\"number\" step=\"0.1\" name=\"passPercent\" min=\"1\" max=\"100\" placeholder=\"Pass %\" class=\"rounded-lg bg-slate-900/70 border border-white/20 px-3 py-2\" required>\n");
      out.write("                </div>\n");
      out.write("                <button class=\"rounded-xl py-2 bg-gradient-to-r from-cyan-400 to-emerald-400 text-slate-900 font-semibold\">Create Test</button>\n");
      out.write("            </form>\n");
      out.write("        </section>\n");
      out.write("\n");
      out.write("        <section class=\"rounded-2xl border border-white/15 bg-white/10 p-5\">\n");
      out.write("            <h2 class=\"font-display text-xl\">Delete Test</h2>\n");
      out.write("            <form method=\"post\" class=\"grid gap-3 mt-3\">\n");
      out.write("                <input type=\"hidden\" name=\"action\" value=\"deleteTest\">\n");
      out.write("                <input name=\"testId\" placeholder=\"Test ID\" class=\"rounded-lg bg-slate-900/70 border border-white/20 px-3 py-2\" required>\n");
      out.write("                <button class=\"rounded-xl py-2 bg-red-500/90 hover:bg-red-500 font-semibold\">Delete Test</button>\n");
      out.write("            </form>\n");
      out.write("        </section>\n");
      out.write("\n");
      out.write("        <section class=\"rounded-2xl border border-white/15 bg-white/10 p-5 lg:col-span-2\">\n");
      out.write("            <h2 class=\"font-display text-xl\">Add Question</h2>\n");
      out.write("            <form method=\"post\" class=\"grid gap-3 mt-3\">\n");
      out.write("                <input type=\"hidden\" name=\"action\" value=\"addQuestion\">\n");
      out.write("                <div class=\"grid sm:grid-cols-2 gap-3\">\n");
      out.write("                    <input name=\"testId\" placeholder=\"Target Test ID\" class=\"rounded-lg bg-slate-900/70 border border-white/20 px-3 py-2\" required>\n");
      out.write("                    <input name=\"qid\" placeholder=\"Question ID\" class=\"rounded-lg bg-slate-900/70 border border-white/20 px-3 py-2\" required>\n");
      out.write("                </div>\n");
      out.write("                <textarea name=\"qtext\" placeholder=\"Question text\" class=\"rounded-lg bg-slate-900/70 border border-white/20 px-3 py-2\" required></textarea>\n");
      out.write("                <div class=\"grid sm:grid-cols-2 gap-3\">\n");
      out.write("                    <input name=\"o1\" placeholder=\"Option 1\" class=\"rounded-lg bg-slate-900/70 border border-white/20 px-3 py-2\" required>\n");
      out.write("                    <input name=\"o2\" placeholder=\"Option 2\" class=\"rounded-lg bg-slate-900/70 border border-white/20 px-3 py-2\" required>\n");
      out.write("                    <input name=\"o3\" placeholder=\"Option 3\" class=\"rounded-lg bg-slate-900/70 border border-white/20 px-3 py-2\" required>\n");
      out.write("                    <input name=\"o4\" placeholder=\"Option 4\" class=\"rounded-lg bg-slate-900/70 border border-white/20 px-3 py-2\" required>\n");
      out.write("                </div>\n");
      out.write("                <input type=\"number\" name=\"answer\" min=\"0\" max=\"3\" placeholder=\"Correct Option Index (0-3)\" class=\"rounded-lg bg-slate-900/70 border border-white/20 px-3 py-2\" required>\n");
      out.write("                <button class=\"rounded-xl py-2 bg-gradient-to-r from-cyan-400 to-emerald-400 text-slate-900 font-semibold\">Add Question</button>\n");
      out.write("            </form>\n");
      out.write("        </section>\n");
      out.write("\n");
      out.write("        <section class=\"rounded-2xl border border-white/15 bg-white/10 p-5 lg:col-span-2\">\n");
      out.write("            <h2 class=\"font-display text-xl\">Delete Question</h2>\n");
      out.write("            <form method=\"post\" class=\"grid sm:grid-cols-3 gap-3 mt-3\">\n");
      out.write("                <input type=\"hidden\" name=\"action\" value=\"deleteQuestion\">\n");
      out.write("                <input name=\"testId\" placeholder=\"Target Test ID\" class=\"rounded-lg bg-slate-900/70 border border-white/20 px-3 py-2\" required>\n");
      out.write("                <input name=\"qid\" placeholder=\"Question ID\" class=\"rounded-lg bg-slate-900/70 border border-white/20 px-3 py-2\" required>\n");
      out.write("                <button class=\"rounded-xl py-2 bg-red-500/90 hover:bg-red-500 font-semibold\">Delete Question</button>\n");
      out.write("            </form>\n");
      out.write("        </section>\n");
      out.write("    </div>\n");
      out.write("\n");
      out.write("    <section class=\"rounded-2xl border border-white/15 bg-white/10 p-5 mt-6\">\n");
      out.write("        <h2 class=\"font-display text-xl\">Current Tests</h2>\n");
      out.write("        <div class=\"overflow-x-auto mt-3\">\n");
      out.write("            <table class=\"w-full min-w-[760px] text-left\">\n");
      out.write("                <thead class=\"text-xs uppercase tracking-[0.12em] text-slate-300\">\n");
      out.write("                <tr>\n");
      out.write("                    <th class=\"py-2\">ID</th>\n");
      out.write("                    <th class=\"py-2\">Name</th>\n");
      out.write("                    <th class=\"py-2\">Duration</th>\n");
      out.write("                    <th class=\"py-2\">Pass %</th>\n");
      out.write("                    <th class=\"py-2\">Questions</th>\n");
      out.write("                </tr>\n");
      out.write("                </thead>\n");
      out.write("                <tbody>\n");
      out.write("                ");
 for (Map<String, Object> t : testCatalog) {
                    List<Map<String, Object>> qs = (List<Map<String, Object>>) t.get("questions");
                
      out.write("\n");
      out.write("                <tr class=\"border-t border-white/10\">\n");
      out.write("                    <td class=\"py-2 font-mono text-xs\">");
      out.print( esc(String.valueOf(t.get("id"))) );
      out.write("</td>\n");
      out.write("                    <td class=\"py-2\">");
      out.print( esc(String.valueOf(t.get("name"))) );
      out.write("</td>\n");
      out.write("                    <td class=\"py-2\">");
      out.print( ((Number) t.get("durationSec")).intValue() / 60 );
      out.write(" min</td>\n");
      out.write("                    <td class=\"py-2\">");
      out.print( String.format("%.1f", ((Number) t.get("passPercent")).doubleValue()) );
      out.write("</td>\n");
      out.write("                    <td class=\"py-2\">");
      out.print( qs.size() );
      out.write("</td>\n");
      out.write("                </tr>\n");
      out.write("                ");
 } 
      out.write("\n");
      out.write("                </tbody>\n");
      out.write("            </table>\n");
      out.write("        </div>\n");
      out.write("        <p class=\"text-slate-400 text-sm mt-3\">Default admin credentials: <span class=\"font-mono\">admin / admin123</span></p>\n");
      out.write("    </section>\n");
      out.write("</div>\n");
      out.write("<script>\n");
      out.write("    function buildAIPrompt() {\n");
      out.write("        const topic = (document.getElementById('aiTopic').value || 'Computer Science').trim();\n");
      out.write("        const level = (document.getElementById('aiLevel').value || 'Intermediate').trim();\n");
      out.write("        const count = (document.getElementById('aiCount').value || '10').trim();\n");
      out.write("        const testId = topic.replace(/[^A-Za-z0-9]/g, '').toUpperCase().substring(0, 6) || 'AITEST';\n");
      out.write("        const lines = [\n");
      out.write("            'Create a multiple-choice exam strictly in the format below.',\n");
      out.write("            'No markdown, no explanation, no extra text.',\n");
      out.write("            'Topic: ' + topic,\n");
      out.write("            'Level: ' + level,\n");
      out.write("            'Question count: ' + count,\n");
      out.write("            '',\n");
      out.write("            'FORMAT (tab-separated for question rows):',\n");
      out.write("            'TEST_ID: ' + testId,\n");
      out.write("            'TEST_NAME: <name>',\n");
      out.write("            'TAGLINE: <short tagline>',\n");
      out.write("            'DURATION_MIN: <integer>',\n");
      out.write("            'PASS_PERCENT: <number 1-100>',\n");
      out.write("            'Q\\\\t<QUESTION_ID>\\\\t<QUESTION_TEXT>\\\\t<OPTION1>\\\\t<OPTION2>\\\\t<OPTION3>\\\\t<OPTION4>\\\\t<CORRECT_OPTION_INDEX_0_TO_3>',\n");
      out.write("            '',\n");
      out.write("            'Rules:',\n");
      out.write("            '- Provide exactly ' + count + ' Q lines',\n");
      out.write("            '- Use unique QUESTION_ID values',\n");
      out.write("            '- Correct index must be 0,1,2 or 3',\n");
      out.write("            '- Keep options concise and unambiguous'\n");
      out.write("        ];\n");
      out.write("        document.getElementById('aiPromptBox').value = lines.join('\\n');\n");
      out.write("    }\n");
      out.write("\n");
      out.write("    function copyAIPrompt() {\n");
      out.write("        const box = document.getElementById('aiPromptBox');\n");
      out.write("        box.select();\n");
      out.write("        document.execCommand('copy');\n");
      out.write("    }\n");
      out.write("</script>\n");
      out.write("</body>\n");
      out.write("</html>\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof jakarta.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
