/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/10.1.52
 * Generated at: 2026-02-11 19:26:45 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import jakarta.servlet.*;
import jakarta.servlet.http.*;
import jakarta.servlet.jsp.*;
import java.util.*;
import java.net.*;
import java.nio.charset.StandardCharsets;
import jakarta.servlet.http.Cookie;

public final class session_002dcookie_002ddemo_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports,
                 org.apache.jasper.runtime.JspSourceDirectives {

  private static final jakarta.servlet.jsp.JspFactory _jspxFactory =
          jakarta.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.LinkedHashSet<>(7);
    _jspx_imports_packages.add("java.util");
    _jspx_imports_packages.add("java.net");
    _jspx_imports_packages.add("jakarta.servlet");
    _jspx_imports_packages.add("jakarta.servlet.http");
    _jspx_imports_packages.add("jakarta.servlet.jsp");
    _jspx_imports_classes = new java.util.LinkedHashSet<>(3);
    _jspx_imports_classes.add("jakarta.servlet.http.Cookie");
    _jspx_imports_classes.add("java.nio.charset.StandardCharsets");
  }

  private volatile jakarta.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public boolean getErrorOnELNotFound() {
    return false;
  }

  public jakarta.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final jakarta.servlet.http.HttpServletRequest request, final jakarta.servlet.http.HttpServletResponse response)
      throws java.io.IOException, jakarta.servlet.ServletException {

    if (!jakarta.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final jakarta.servlet.jsp.PageContext pageContext;
    jakarta.servlet.http.HttpSession session = null;
    final jakarta.servlet.ServletContext application;
    final jakarta.servlet.ServletConfig config;
    jakarta.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    jakarta.servlet.jsp.JspWriter _jspx_out = null;
    jakarta.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write('\n');

    request.setCharacterEncoding("UTF-8");
    String action = request.getParameter("action");
    if (action == null) {
        action = "";
    }

    String status = "Ready";

    if ("setCookie".equals(action)) {
        String cookieName = request.getParameter("cookieName");
        String cookieValue = request.getParameter("cookieValue");
        String maxAgeStr = request.getParameter("cookieMaxAge");

        if (cookieName != null && !cookieName.trim().isEmpty()) {
            int maxAge = 3600;
            try {
                if (maxAgeStr != null && !maxAgeStr.trim().isEmpty()) {
                    maxAge = Integer.parseInt(maxAgeStr.trim());
                }
            } catch (NumberFormatException ignore) {
                maxAge = 3600;
            }

            String encodedValue = URLEncoder.encode(cookieValue == null ? "" : cookieValue, StandardCharsets.UTF_8);
            try {
                Cookie cookie = new Cookie(cookieName.trim(), encodedValue);
                cookie.setMaxAge(maxAge);
                cookie.setPath(request.getContextPath().isEmpty() ? "/" : request.getContextPath());
                response.addCookie(cookie);
                status = "Cookie set: " + cookieName + " (maxAge=" + maxAge + "s)";
            } catch (IllegalArgumentException ex) {
                status = "Invalid cookie: " + ex.getMessage();
            }
        } else {
            status = "Cookie name is required.";
        }
    } else if ("deleteCookie".equals(action)) {
        String cookieName = request.getParameter("cookieName");
        if (cookieName != null && !cookieName.trim().isEmpty()) {
            Cookie cookie = new Cookie(cookieName.trim(), "");
            cookie.setMaxAge(0);
            cookie.setPath(request.getContextPath().isEmpty() ? "/" : request.getContextPath());
            response.addCookie(cookie);
            status = "Cookie deleted: " + cookieName;
        } else {
            status = "Cookie name is required to delete.";
        }
    } else if ("setSession".equals(action)) {
        String sessionKey = request.getParameter("sessionKey");
        String sessionValue = request.getParameter("sessionValue");
        if (sessionKey != null && !sessionKey.trim().isEmpty()) {
            session.setAttribute(sessionKey.trim(), sessionValue == null ? "" : sessionValue);
            status = "Session attribute set: " + sessionKey;
        } else {
            status = "Session key is required.";
        }
    } else if ("removeSession".equals(action)) {
        String sessionKey = request.getParameter("sessionKey");
        if (sessionKey != null && !sessionKey.trim().isEmpty()) {
            session.removeAttribute(sessionKey.trim());
            status = "Session attribute removed: " + sessionKey;
        } else {
            status = "Session key is required to remove.";
        }
    } else if ("invalidateSession".equals(action)) {
        session.invalidate();
        HttpSession newSession = request.getSession(true);
        status = "Session invalidated. New session ID: " + newSession.getId();
    }

    String statusJs = status == null ? "" : status
            .replace("\\", "\\\\")
            .replace("\"", "\\\"")
            .replace("\r", "\\r")
            .replace("\n", "\\n")
            .replace("</", "<\\/");

    Cookie[] cookies = request.getCookies();
    List<Cookie> cookieList = new ArrayList<Cookie>();
    if (cookies != null) {
        cookieList = Arrays.asList(cookies);
    }

    List<String> sessionKeys = new ArrayList<String>();
    Enumeration<String> names = session.getAttributeNames();
    while (names.hasMoreElements()) {
        sessionKeys.add(names.nextElement());
    }

      out.write("\n");
      out.write("<!DOCTYPE html>\n");
      out.write("<html lang=\"en\">\n");
      out.write("<head>\n");
      out.write("    <meta charset=\"UTF-8\">\n");
      out.write("    <meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">\n");
      out.write("    <title>JSP Cookies & Session Playground</title>\n");
      out.write("    <style>\n");
      out.write("        :root {\n");
      out.write("            --bg: #f3f8ff;\n");
      out.write("            --panel: #ffffff;\n");
      out.write("            --ink: #102a43;\n");
      out.write("            --muted: #486581;\n");
      out.write("            --brand: #0f8b8d;\n");
      out.write("            --brand-dark: #0b6470;\n");
      out.write("            --accent: #f0b429;\n");
      out.write("            --danger: #d64545;\n");
      out.write("            --line: #d9e2ec;\n");
      out.write("            --ok: #1f9d55;\n");
      out.write("        }\n");
      out.write("\n");
      out.write("        * { box-sizing: border-box; }\n");
      out.write("\n");
      out.write("        body {\n");
      out.write("            margin: 0;\n");
      out.write("            font-family: \"Segoe UI\", \"Trebuchet MS\", sans-serif;\n");
      out.write("            color: var(--ink);\n");
      out.write("            background:\n");
      out.write("                radial-gradient(circle at 20% 0%, #c7eff0 0%, transparent 35%),\n");
      out.write("                radial-gradient(circle at 90% 20%, #fff0cf 0%, transparent 30%),\n");
      out.write("                var(--bg);\n");
      out.write("            min-height: 100vh;\n");
      out.write("            padding: 28px 14px;\n");
      out.write("        }\n");
      out.write("\n");
      out.write("        .container {\n");
      out.write("            max-width: 1100px;\n");
      out.write("            margin: 0 auto;\n");
      out.write("            display: grid;\n");
      out.write("            gap: 16px;\n");
      out.write("        }\n");
      out.write("\n");
      out.write("        .card {\n");
      out.write("            background: var(--panel);\n");
      out.write("            border: 1px solid var(--line);\n");
      out.write("            border-radius: 14px;\n");
      out.write("            padding: 16px;\n");
      out.write("            box-shadow: 0 10px 26px rgba(16, 42, 67, 0.08);\n");
      out.write("        }\n");
      out.write("\n");
      out.write("        h1 {\n");
      out.write("            margin: 0 0 8px;\n");
      out.write("            font-size: 1.75rem;\n");
      out.write("        }\n");
      out.write("\n");
      out.write("        h2 {\n");
      out.write("            margin: 0 0 10px;\n");
      out.write("            font-size: 1.05rem;\n");
      out.write("            color: var(--brand-dark);\n");
      out.write("        }\n");
      out.write("\n");
      out.write("        p { margin: 6px 0; color: var(--muted); }\n");
      out.write("\n");
      out.write("        .status {\n");
      out.write("            border-left: 4px solid var(--ok);\n");
      out.write("            padding: 10px 12px;\n");
      out.write("            background: #effcf4;\n");
      out.write("            border-radius: 8px;\n");
      out.write("            font-weight: 600;\n");
      out.write("            color: #1a7f43;\n");
      out.write("        }\n");
      out.write("\n");
      out.write("        .grid {\n");
      out.write("            display: grid;\n");
      out.write("            grid-template-columns: repeat(auto-fit, minmax(280px, 1fr));\n");
      out.write("            gap: 16px;\n");
      out.write("        }\n");
      out.write("\n");
      out.write("        form {\n");
      out.write("            display: grid;\n");
      out.write("            gap: 10px;\n");
      out.write("            margin-bottom: 12px;\n");
      out.write("            padding: 12px;\n");
      out.write("            border: 1px solid var(--line);\n");
      out.write("            border-radius: 10px;\n");
      out.write("            background: #fbfdff;\n");
      out.write("        }\n");
      out.write("\n");
      out.write("        label { font-size: 0.92rem; font-weight: 600; }\n");
      out.write("\n");
      out.write("        input {\n");
      out.write("            width: 100%;\n");
      out.write("            border: 1px solid #bcccdc;\n");
      out.write("            border-radius: 8px;\n");
      out.write("            padding: 9px 10px;\n");
      out.write("            font-size: 0.95rem;\n");
      out.write("        }\n");
      out.write("\n");
      out.write("        .btn-row {\n");
      out.write("            display: flex;\n");
      out.write("            flex-wrap: wrap;\n");
      out.write("            gap: 8px;\n");
      out.write("            margin-top: 4px;\n");
      out.write("        }\n");
      out.write("\n");
      out.write("        button {\n");
      out.write("            border: 0;\n");
      out.write("            border-radius: 8px;\n");
      out.write("            padding: 9px 12px;\n");
      out.write("            font-weight: 700;\n");
      out.write("            cursor: pointer;\n");
      out.write("            color: #fff;\n");
      out.write("            background: var(--brand);\n");
      out.write("        }\n");
      out.write("\n");
      out.write("        button.secondary { background: #627d98; }\n");
      out.write("        button.warn { background: var(--danger); }\n");
      out.write("        button:hover { opacity: 0.95; }\n");
      out.write("\n");
      out.write("        table {\n");
      out.write("            width: 100%;\n");
      out.write("            border-collapse: collapse;\n");
      out.write("            font-size: 0.92rem;\n");
      out.write("        }\n");
      out.write("\n");
      out.write("        th, td {\n");
      out.write("            border: 1px solid var(--line);\n");
      out.write("            padding: 8px;\n");
      out.write("            text-align: left;\n");
      out.write("            vertical-align: top;\n");
      out.write("        }\n");
      out.write("\n");
      out.write("        th {\n");
      out.write("            background: #f0f4f8;\n");
      out.write("            color: var(--brand-dark);\n");
      out.write("        }\n");
      out.write("\n");
      out.write("        code {\n");
      out.write("            background: #f0f4f8;\n");
      out.write("            border-radius: 5px;\n");
      out.write("            padding: 2px 5px;\n");
      out.write("        }\n");
      out.write("\n");
      out.write("        .meta {\n");
      out.write("            display: flex;\n");
      out.write("            flex-wrap: wrap;\n");
      out.write("            gap: 8px;\n");
      out.write("            margin-top: 6px;\n");
      out.write("            font-size: 0.9rem;\n");
      out.write("        }\n");
      out.write("\n");
      out.write("        .pill {\n");
      out.write("            background: #e6f7fb;\n");
      out.write("            border: 1px solid #9bd6df;\n");
      out.write("            border-radius: 999px;\n");
      out.write("            padding: 6px 10px;\n");
      out.write("            color: #0b6470;\n");
      out.write("            font-weight: 600;\n");
      out.write("        }\n");
      out.write("    </style>\n");
      out.write("</head>\n");
      out.write("<body>\n");
      out.write("    <div class=\"container\">\n");
      out.write("        <div class=\"card\">\n");
      out.write("            <h1>JSP Cookies + Session Playground</h1>\n");
      out.write("            <p>Use this page to set, remove, and inspect cookies and session attributes in one place.</p>\n");
      out.write("            <div class=\"status\">");
      out.print( status );
      out.write("</div>\n");
      out.write("            <div class=\"meta\">\n");
      out.write("                <span class=\"pill\">Session ID: <code>");
      out.print( session.getId() );
      out.write("</code></span>\n");
      out.write("                <span class=\"pill\">Context Path: <code>");
      out.print( request.getContextPath().isEmpty() ? "/" : request.getContextPath() );
      out.write("</code></span>\n");
      out.write("                <span class=\"pill\">Current Time: <code>");
      out.print( new java.util.Date() );
      out.write("</code></span>\n");
      out.write("            </div>\n");
      out.write("        </div>\n");
      out.write("\n");
      out.write("        <div class=\"grid\">\n");
      out.write("            <div class=\"card\">\n");
      out.write("                <h2>Cookie Actions</h2>\n");
      out.write("                <form method=\"post\">\n");
      out.write("                    <input type=\"hidden\" name=\"action\" value=\"setCookie\" />\n");
      out.write("                    <div>\n");
      out.write("                        <label for=\"cookieName\">Cookie Name</label>\n");
      out.write("                        <input id=\"cookieName\" name=\"cookieName\" placeholder=\"exampleCookie\" required />\n");
      out.write("                    </div>\n");
      out.write("                    <div>\n");
      out.write("                        <label for=\"cookieValue\">Cookie Value</label>\n");
      out.write("                        <input id=\"cookieValue\" name=\"cookieValue\" placeholder=\"hello-cookie\" />\n");
      out.write("                    </div>\n");
      out.write("                    <div>\n");
      out.write("                        <label for=\"cookieMaxAge\">Max Age (seconds)</label>\n");
      out.write("                        <input id=\"cookieMaxAge\" name=\"cookieMaxAge\" value=\"3600\" type=\"number\" min=\"0\" />\n");
      out.write("                    </div>\n");
      out.write("                    <div class=\"btn-row\">\n");
      out.write("                        <button type=\"submit\">Set Cookie</button>\n");
      out.write("                    </div>\n");
      out.write("                </form>\n");
      out.write("\n");
      out.write("                <form method=\"post\">\n");
      out.write("                    <input type=\"hidden\" name=\"action\" value=\"deleteCookie\" />\n");
      out.write("                    <div>\n");
      out.write("                        <label for=\"deleteCookieName\">Cookie Name to Delete</label>\n");
      out.write("                        <input id=\"deleteCookieName\" name=\"cookieName\" placeholder=\"exampleCookie\" required />\n");
      out.write("                    </div>\n");
      out.write("                    <div class=\"btn-row\">\n");
      out.write("                        <button class=\"warn\" type=\"submit\">Delete Cookie</button>\n");
      out.write("                    </div>\n");
      out.write("                </form>\n");
      out.write("            </div>\n");
      out.write("\n");
      out.write("            <div class=\"card\">\n");
      out.write("                <h2>Session Actions</h2>\n");
      out.write("                <form method=\"post\">\n");
      out.write("                    <input type=\"hidden\" name=\"action\" value=\"setSession\" />\n");
      out.write("                    <div>\n");
      out.write("                        <label for=\"sessionKey\">Session Key</label>\n");
      out.write("                        <input id=\"sessionKey\" name=\"sessionKey\" placeholder=\"username\" required />\n");
      out.write("                    </div>\n");
      out.write("                    <div>\n");
      out.write("                        <label for=\"sessionValue\">Session Value</label>\n");
      out.write("                        <input id=\"sessionValue\" name=\"sessionValue\" placeholder=\"Rohit\" />\n");
      out.write("                    </div>\n");
      out.write("                    <div class=\"btn-row\">\n");
      out.write("                        <button type=\"submit\">Set Session Value</button>\n");
      out.write("                    </div>\n");
      out.write("                </form>\n");
      out.write("\n");
      out.write("                <form method=\"post\">\n");
      out.write("                    <input type=\"hidden\" name=\"action\" value=\"removeSession\" />\n");
      out.write("                    <div>\n");
      out.write("                        <label for=\"removeSessionKey\">Session Key to Remove</label>\n");
      out.write("                        <input id=\"removeSessionKey\" name=\"sessionKey\" placeholder=\"username\" required />\n");
      out.write("                    </div>\n");
      out.write("                    <div class=\"btn-row\">\n");
      out.write("                        <button class=\"secondary\" type=\"submit\">Remove Session Key</button>\n");
      out.write("                    </div>\n");
      out.write("                </form>\n");
      out.write("\n");
      out.write("                <form method=\"post\">\n");
      out.write("                    <input type=\"hidden\" name=\"action\" value=\"invalidateSession\" />\n");
      out.write("                    <div class=\"btn-row\">\n");
      out.write("                        <button class=\"warn\" type=\"submit\">Invalidate Session</button>\n");
      out.write("                    </div>\n");
      out.write("                </form>\n");
      out.write("            </div>\n");
      out.write("        </div>\n");
      out.write("\n");
      out.write("        <div class=\"grid\">\n");
      out.write("            <div class=\"card\">\n");
      out.write("                <h2>Current Cookies (Server Side)</h2>\n");
      out.write("                <table>\n");
      out.write("                    <thead>\n");
      out.write("                        <tr>\n");
      out.write("                            <th>Name</th>\n");
      out.write("                            <th>Value</th>\n");
      out.write("                            <th>Path</th>\n");
      out.write("                            <th>Max Age</th>\n");
      out.write("                        </tr>\n");
      out.write("                    </thead>\n");
      out.write("                    <tbody>\n");
      out.write("                    ");

                        if (cookieList.isEmpty()) {
                    
      out.write("\n");
      out.write("                        <tr><td colspan=\"4\">No cookies found for this request.</td></tr>\n");
      out.write("                    ");

                        } else {
                            for (Cookie c : cookieList) {
                    
      out.write("\n");
      out.write("                        <tr>\n");
      out.write("                            <td>");
      out.print( c.getName() );
      out.write("</td>\n");
      out.write("                            <td>");

                                String decodedValue = c.getValue();
                                try {
                                    decodedValue = URLDecoder.decode(c.getValue(), StandardCharsets.UTF_8);
                                } catch (IllegalArgumentException ignore) {
                                    decodedValue = c.getValue();
                                }
                                out.print(decodedValue);
                            
      out.write("</td>\n");
      out.write("                            <td>");
      out.print( c.getPath() == null ? "(not set)" : c.getPath() );
      out.write("</td>\n");
      out.write("                            <td>");
      out.print( c.getMaxAge() );
      out.write("</td>\n");
      out.write("                        </tr>\n");
      out.write("                    ");

                            }
                        }
                    
      out.write("\n");
      out.write("                    </tbody>\n");
      out.write("                </table>\n");
      out.write("            </div>\n");
      out.write("\n");
      out.write("            <div class=\"card\">\n");
      out.write("                <h2>Current Session Attributes</h2>\n");
      out.write("                <table>\n");
      out.write("                    <thead>\n");
      out.write("                        <tr>\n");
      out.write("                            <th>Key</th>\n");
      out.write("                            <th>Value</th>\n");
      out.write("                        </tr>\n");
      out.write("                    </thead>\n");
      out.write("                    <tbody>\n");
      out.write("                    ");

                        if (sessionKeys.isEmpty()) {
                    
      out.write("\n");
      out.write("                        <tr><td colspan=\"2\">No session attributes set.</td></tr>\n");
      out.write("                    ");

                        } else {
                            for (String key : sessionKeys) {
                    
      out.write("\n");
      out.write("                        <tr>\n");
      out.write("                            <td>");
      out.print( key );
      out.write("</td>\n");
      out.write("                            <td>");
      out.print( String.valueOf(session.getAttribute(key)) );
      out.write("</td>\n");
      out.write("                        </tr>\n");
      out.write("                    ");

                            }
                        }
                    
      out.write("\n");
      out.write("                    </tbody>\n");
      out.write("                </table>\n");
      out.write("            </div>\n");
      out.write("        </div>\n");
      out.write("    </div>\n");
      out.write("\n");
      out.write("    <script>\n");
      out.write("        (function () {\n");
      out.write("            const cookieDump = document.cookie || \"(no client-side cookies visible)\";\n");
      out.write("            const sessionId = \"");
      out.print( session.getId() );
      out.write("\";\n");
      out.write("            const statusText = \"");
      out.print( statusJs );
      out.write("\";\n");
      out.write("\n");
      out.write("            console.group(\"JSP Playground Debug\");\n");
      out.write("            console.log(\"Status:\", statusText);\n");
      out.write("            console.log(\"Session ID:\", sessionId);\n");
      out.write("            console.log(\"document.cookie:\", cookieDump);\n");
      out.write("            console.log(\"Request method:\", \"");
      out.print( request.getMethod() );
      out.write("\");\n");
      out.write("            console.groupEnd();\n");
      out.write("        })();\n");
      out.write("    </script>\n");
      out.write("</body>\n");
      out.write("</html>\r\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof jakarta.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
