/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/10.1.52
 * Generated at: 2026-02-13 18:28:11 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import jakarta.servlet.*;
import jakarta.servlet.http.*;
import jakarta.servlet.jsp.*;
import java.util.*;
import java.security.MessageDigest;
import java.nio.charset.StandardCharsets;
import java.net.URLEncoder;

public final class submit_002dexam_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports,
                 org.apache.jasper.runtime.JspSourceDirectives {


    public String hashPassword(String input) {
        try {
            MessageDigest md = MessageDigest.getInstance("SHA-256");
            byte[] digest = md.digest(input.getBytes(StandardCharsets.UTF_8));
            StringBuilder sb = new StringBuilder();
            for (byte b : digest) {
                sb.append(String.format("%02x", b));
            }
            return sb.toString();
        } catch (Exception e) {
            return "";
        }
    }

    public String esc(String value) {
        if (value == null) {
            return "";
        }
        return value.replace("&", "&amp;")
                .replace("<", "&lt;")
                .replace(">", "&gt;")
                .replace("\"", "&quot;")
                .replace("'", "&#39;");
    }

    public boolean isLoggedIn(HttpSession session) {
        return session.getAttribute("authUser") != null;
    }

    public String currentUser(HttpSession session) {
        Object u = session.getAttribute("authUser");
        return u == null ? null : String.valueOf(u);
    }

    public boolean isAdmin(HttpSession session) {
        Object role = session.getAttribute("authRole");
        return role != null && "admin".equals(String.valueOf(role));
    }

    public Map<String, Object> q(String id, String text, String[] options, int answer) {
        Map<String, Object> question = new HashMap<String, Object>();
        question.put("id", id);
        question.put("text", text);
        question.put("options", options);
        question.put("answer", answer);
        return question;
    }

    public Map<String, Object> test(String id, String name, String tagline, int durationSec, double passPercent, List<Map<String, Object>> questions) {
        Map<String, Object> exam = new HashMap<String, Object>();
        exam.put("id", id);
        exam.put("name", name);
        exam.put("tagline", tagline);
        exam.put("durationSec", durationSec);
        exam.put("passPercent", passPercent);
        exam.put("questions", questions);
        return exam;
    }

  private static final jakarta.servlet.jsp.JspFactory _jspxFactory =
          jakarta.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(1);
    _jspx_dependants.put("/exam-common.jspf", Long.valueOf(1771007077865L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.LinkedHashSet<>(6);
    _jspx_imports_packages.add("java.util");
    _jspx_imports_packages.add("jakarta.servlet");
    _jspx_imports_packages.add("jakarta.servlet.http");
    _jspx_imports_packages.add("jakarta.servlet.jsp");
    _jspx_imports_classes = new java.util.LinkedHashSet<>(4);
    _jspx_imports_classes.add("java.net.URLEncoder");
    _jspx_imports_classes.add("java.security.MessageDigest");
    _jspx_imports_classes.add("java.nio.charset.StandardCharsets");
  }

  private volatile jakarta.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public boolean getErrorOnELNotFound() {
    return false;
  }

  public jakarta.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final jakarta.servlet.http.HttpServletRequest request, final jakarta.servlet.http.HttpServletResponse response)
      throws java.io.IOException, jakarta.servlet.ServletException {

    if (!jakarta.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final jakarta.servlet.jsp.PageContext pageContext;
    jakarta.servlet.http.HttpSession session = null;
    final jakarta.servlet.ServletContext application;
    final jakarta.servlet.ServletConfig config;
    jakarta.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    jakarta.servlet.jsp.JspWriter _jspx_out = null;
    jakarta.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write('\n');
      out.write('\n');
      out.write('\n');

    request.setCharacterEncoding("UTF-8");

    synchronized (application) {
        if (application.getAttribute("users") == null) {
            application.setAttribute("users", new HashMap<String, Map<String, String>>());
        }
        if (application.getAttribute("attempts") == null) {
            application.setAttribute("attempts", new ArrayList<Map<String, Object>>());
        }
        if (application.getAttribute("testCatalog") == null) {
            List<Map<String, Object>> catalog = new ArrayList<Map<String, Object>>();

            List<Map<String, Object>> t1 = new ArrayList<Map<String, Object>>();
            t1.add(q("F1", "Which protocol encrypts website traffic by default?", new String[]{"HTTP", "FTP", "HTTPS", "IMAP"}, 2));
            t1.add(q("F2", "Which data structure follows Last-In-First-Out order?", new String[]{"Queue", "Stack", "Tree", "Graph"}, 1));
            t1.add(q("F3", "What does SQL stand for?", new String[]{"Structured Query Language", "Simple Query Logic", "Secure Queue Layer", "System Query Link"}, 0));
            t1.add(q("F4", "Which Java keyword creates a subclass from a parent class?", new String[]{"extends", "implements", "inherits", "super"}, 0));
            t1.add(q("F5", "Big-O for binary search on sorted data is", new String[]{"O(n)", "O(log n)", "O(n log n)", "O(1)"}, 1));
            t1.add(q("F6", "Which HTML tag is used for the largest heading?", new String[]{"<head>", "<h6>", "<h1>", "<header>"}, 2));
            t1.add(q("F7", "Which SQL clause filters rows before grouping?", new String[]{"HAVING", "ORDER BY", "GROUP BY", "WHERE"}, 3));
            t1.add(q("F8", "Which of these is a NoSQL database?", new String[]{"MySQL", "PostgreSQL", "MongoDB", "Oracle"}, 2));
            t1.add(q("F9", "In CSS, which property controls text color?", new String[]{"font-color", "text-color", "color", "foreground"}, 2));
            t1.add(q("F10", "Which HTTP status means Not Found?", new String[]{"200", "302", "401", "404"}, 3));
            t1.add(q("F11", "Which command in Git uploads local commits to remote?", new String[]{"git clone", "git pull", "git push", "git merge"}, 2));
            t1.add(q("F12", "Which one is a strongly typed language?", new String[]{"Java", "HTML", "CSS", "SQL"}, 0));
            catalog.add(test("FOUND", "Foundations Assessment", "Core software and web fundamentals", 12 * 60, 55.0, t1));

            List<Map<String, Object>> t2 = new ArrayList<Map<String, Object>>();
            t2.add(q("A1", "Which model architecture powers most modern LLM chat systems?", new String[]{"CNN", "Transformer", "RNN", "SVM"}, 1));
            t2.add(q("A2", "Precision measures", new String[]{"Correct positives among predicted positives", "Correct positives among all actual positives", "Overall correctness", "Training speed"}, 0));
            t2.add(q("A3", "Overfitting means", new String[]{"Model performs well on unseen data", "Model memorizes training data and generalizes poorly", "Model uses too little data", "Model has low variance"}, 1));
            t2.add(q("A4", "Which task is supervised learning?", new String[]{"Clustering customers", "Dimensionality reduction", "Spam classification", "Topic modeling"}, 2));
            t2.add(q("A5", "Gradient descent updates parameters using", new String[]{"Random guessing", "Loss gradients", "Manual tuning", "Hash maps"}, 1));
            t2.add(q("A6", "A confusion matrix is used for", new String[]{"Database joins", "Classification evaluation", "Network routing", "Code linting"}, 1));
            t2.add(q("A7", "Which metric is better for imbalanced binary classes?", new String[]{"Accuracy only", "F1 score", "Epoch count", "Latency"}, 1));
            t2.add(q("A8", "Tokenization in NLP is", new String[]{"Encrypting text", "Breaking text into units", "Compressing images", "Balancing labels"}, 1));
            t2.add(q("A9", "ReLU is", new String[]{"A loss function", "An optimizer", "An activation function", "A tokenizer"}, 2));
            t2.add(q("A10", "Train/validation split helps", new String[]{"Detect generalization", "Speed up hardware", "Avoid using labels", "Remove features"}, 0));
            catalog.add(test("AI", "AI Systems Readiness", "Applied ML, evaluation and deployment concepts", 10 * 60, 60.0, t2));

            List<Map<String, Object>> t3 = new ArrayList<Map<String, Object>>();
            t3.add(q("C1", "Which attack injects malicious SQL statements?", new String[]{"DDoS", "XSS", "SQL Injection", "CSRF"}, 2));
            t3.add(q("C2", "MFA stands for", new String[]{"Managed Firewall Access", "Multi-Factor Authentication", "Master File Allocation", "Main Function API"}, 1));
            t3.add(q("C3", "Principle of least privilege means", new String[]{"Give all users admin", "Grant minimum required access", "Share credentials", "Disable logging"}, 1));
            t3.add(q("C4", "Which header reduces XSS risk in browsers?", new String[]{"Content-Security-Policy", "Cache-Control", "ETag", "Accept-Language"}, 0));
            t3.add(q("C5", "Brute force protection usually includes", new String[]{"Unlimited retries", "Rate limiting and lockout", "Plain text passwords", "Open ports"}, 1));
            t3.add(q("C6", "Which one is symmetric encryption?", new String[]{"RSA", "ECC", "AES", "DSA"}, 2));
            t3.add(q("C7", "Phishing primarily targets", new String[]{"Hardware heat", "Human trust", "Compiler speed", "DNS TTL"}, 1));
            t3.add(q("C8", "Which log is key for incident response?", new String[]{"Authentication logs", "Font logs", "Theme logs", "Cache logos"}, 0));
            t3.add(q("C9", "HTTPS certificate validation helps prevent", new String[]{"MITM attacks", "Memory leaks", "Race conditions", "Deadlocks"}, 0));
            t3.add(q("C10", "A secure password should be", new String[]{"Short and reused", "Long and unique", "Only numeric", "Stored in plain text"}, 1));
            catalog.add(test("CYBER", "Cyber Operations Drill", "Security, authentication and secure web operations", 9 * 60, 65.0, t3));

            application.setAttribute("testCatalog", catalog);
            application.setAttribute("questionBank", t1);
        }
    }

    Map<String, Map<String, String>> users = (Map<String, Map<String, String>>) application.getAttribute("users");
    List<Map<String, Object>> attempts = (List<Map<String, Object>>) application.getAttribute("attempts");
    List<Map<String, Object>> testCatalog = (List<Map<String, Object>>) application.getAttribute("testCatalog");

    synchronized (application) {
        if (!users.containsKey("admin")) {
            Map<String, String> admin = new HashMap<String, String>();
            admin.put("fullName", "System Admin");
            admin.put("username", "admin");
            admin.put("passwordHash", hashPassword("admin123"));
            admin.put("createdAt", new Date().toString());
            admin.put("role", "admin");
            users.put("admin", admin);
        }
    }

    Map<String, Map<String, Object>> testIndex = new HashMap<String, Map<String, Object>>();
    int totalQuestionsAcrossTests = 0;
    for (Map<String, Object> t : testCatalog) {
        String testId = String.valueOf(t.get("id"));
        testIndex.put(testId, t);
        List<Map<String, Object>> qs = (List<Map<String, Object>>) t.get("questions");
        totalQuestionsAcrossTests += qs.size();
    }

      out.write('\r');
      out.write('\n');
      out.write('\n');

    if (!isLoggedIn(session)) {
        response.sendRedirect("login.jsp");
        return;
    }

    String activeAttemptId = (String) session.getAttribute("examAttemptId");
    Long startTs = (Long) session.getAttribute("examStartTs");
    Integer examDuration = (Integer) session.getAttribute("examDurationSec");
    String examTestId = (String) session.getAttribute("examTestId");
    Double passPercent = (Double) session.getAttribute("examPassPercent");

    if (activeAttemptId == null || startTs == null || examDuration == null || examTestId == null) {
        response.sendRedirect("dashboard.jsp");
        return;
    }

    String postedAttemptId = request.getParameter("attemptId");
    if (postedAttemptId == null || !postedAttemptId.equals(activeAttemptId)) {
        response.sendRedirect("take-exam.jsp?test=" + URLEncoder.encode(examTestId, "UTF-8"));
        return;
    }

    Map<String, Object> examTest = testIndex.get(examTestId);
    if (examTest == null) {
        response.sendRedirect("dashboard.jsp");
        return;
    }

    List<Map<String, Object>> questions = (List<Map<String, Object>>) examTest.get("questions");

    Map<String, Integer> answers = new HashMap<String, Integer>();
    List<Map<String, Object>> review = new ArrayList<Map<String, Object>>();

    int score = 0;
    int total = questions.size();

    for (Map<String, Object> q : questions) {
        String qid = String.valueOf(q.get("id"));
        String selected = request.getParameter(qid);
        int selectedIndex = -1;
        try {
            if (selected != null) {
                selectedIndex = Integer.parseInt(selected);
            }
        } catch (NumberFormatException ignore) {
            selectedIndex = -1;
        }
        answers.put(qid, selectedIndex);

        int correct = (Integer) q.get("answer");
        boolean isCorrect = (selectedIndex == correct);
        if (isCorrect) {
            score++;
        }

        Map<String, Object> row = new HashMap<String, Object>();
        row.put("qid", qid);
        row.put("question", q.get("text"));
        row.put("options", q.get("options"));
        row.put("selected", selectedIndex);
        row.put("correct", correct);
        row.put("isCorrect", isCorrect);
        review.add(row);
    }

    long submittedAt = System.currentTimeMillis();
    long allowedEnd = startTs + (examDuration * 1000L);
    if (submittedAt > allowedEnd) {
        submittedAt = allowedEnd;
    }

    double percent = total == 0 ? 0.0 : (score * 100.0 / total);
    double threshold = passPercent == null ? ((Number) examTest.get("passPercent")).doubleValue() : passPercent.doubleValue();
    boolean passed = percent >= threshold;

    Map<String, Object> attempt = new HashMap<String, Object>();
    attempt.put("attemptId", activeAttemptId);
    attempt.put("username", currentUser(session));
    attempt.put("fullName", session.getAttribute("authName"));
    attempt.put("testId", examTestId);
    attempt.put("testName", String.valueOf(examTest.get("name")));
    attempt.put("passPercent", threshold);
    attempt.put("durationSec", examDuration);
    attempt.put("score", score);
    attempt.put("total", total);
    attempt.put("percent", percent);
    attempt.put("passed", passed);
    attempt.put("startTs", startTs);
    attempt.put("endTs", submittedAt);
    attempt.put("answers", answers);
    attempt.put("review", review);
    attempts.add(attempt);

    session.removeAttribute("examStartTs");
    session.removeAttribute("examDurationSec");
    session.removeAttribute("examAttemptId");
    session.removeAttribute("examTestId");
    session.removeAttribute("examPassPercent");

    response.sendRedirect("result.jsp?attemptId=" + URLEncoder.encode(activeAttemptId, "UTF-8"));

      out.write('\r');
      out.write('\n');
    } catch (java.lang.Throwable t) {
      if (!(t instanceof jakarta.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
